name: Healthcheck

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  ping_the_app:
    runs-on: ubuntu-latest
    steps:
      - name: Pokedex healthcheck
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://full-stack-open-pokedex-gasw.onrender.com
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
